### PR TITLE
Swift syntax update

### PR DESCRIPTION
**Pull request by stian-a-johansen**

### CODE REVIEW

**Comment by cbpowell** [comment]
Awesome, thanks! I'm going to bring MarqueeLabel-Swift up to parity with the Objective-C version, and then I'll pull this in.

**Comment by stian-a-johansen** [comment]
Cool! Thanks for your work!

**Comment by cbpowell** [comment]
Merged this in, thanks! I had some trouble making sure git credited you for the commit, but got it to work - wanted to make sure you got your contributor credit!

**Comment by stian-a-johansen** [comment]
ah it wasn't really necessary with the credit, it was a very small change. But thanks for doing it!

**Pull request merged**
