### PR TITLE
Fixed scrollDuration and scrollRate setting each other to nil

### PR DESCRIPTION
**Pull request by yonaskolb**

### CODE REVIEW

**Comment by cbpowell** [comment]
Actually this code is functioning as intended (unless you ran into a bug!) - you can only set one or the other, so setting one nils the other out. It's some holdover from the Objective-C code, although it occurs to me that this could be a good usage for Swift's enums with values.

**Comment by yonaskolb** [comment]
I understand that they are supposed to set the other property to nill, but only once, because in the current state if you set scrollRate to something like 3, then it will set scrollDuration to nill, which will then in turn set scrollRate to nill again. This pull request fixes that from happening

**Comment by cbpowell** [comment]
Hah, now I see what you're getting at - good catch. I'll merge it in!

**Comment by cbpowell** [comment]
Also as I mentioned in my original reply, I created the `speed` property in [release 2.6.0](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.6.0) that uses an enum with associated values to encapsulate both the scroll speed type and the magnitude. The `scrollRate` and `scrollDuration` properties still work, although I'll eventually mark them as deprecated.

**Comment by GoodBrue** [comment]
Can you give me an example of how to set the speed? The enum is confusing to me.

**Comment by toshi0383** [comment]
Maybe this one ?
https://github.com/cbpowell/MarqueeLabel-Swift/blob/master/MarqueeLabelDemo-Swift/Demo-tvOS/ViewController.swift#L72

**Comment by GoodBrue** [comment]
How do I access the rate from the MarqueeLabel speed for getting and setting?
I want to get the current scroll rate and add an amount x to it to speed it up or slow it down.

```
    label.speed = label.speed + x
```

The line generates the error "Binary operator '+' cannot be applied to operands of type
'MarqueeLabel.SpeedLimit' and 'CGFloat'. "

**Comment by GoodBrue** [comment]
I figured it out. What a PITA! If there's a cleaner/better way, please tell me. Here's what I did:

```
    // label.speed = label.speed + x
    var rate: CGFloat
    switch label.speed {
    case .Rate(let scrollRate):
        rate = scrollRate
        rate = rate + x
        if rate < 0.0 {
            rate = 0.0
        }
        label.speed = .Rate(rate)
    case .Duration(let scrollDuration):
        rate = scrollDuration
        rate = rate + x
        if rate < 0.0 {
            rate = 0.0
        }
        label.speed = .Duration(rate)
    }
```

**Comment by cbpowell** [comment]
I hadn't considered that use case, the enum does complicate that somewhat. For now you can totally still use the `scrollRate` and `scrollDuration` properties though, which should let you use mathematical operators I think.

I'm going to read a little bit about enums with associated values and see if there's a nice clean way, just out of my own curiosity. I think one way might be to create an extension to the `SpeedLimit` enum type, and add a function like `incrementBy(x: CGFloat)` that encapsulates that code above:

``` swift
// Caveat: I didn't write this in Xcode...
// It may need to be fixed and definitely needs to be tested
extension SpeedLabel {
    mutating func incrementBy(x: CGFloat) {
        switch self {
        case .Rate(let rate):
            let newRate = min(rate + x, 0.0)
            self = .Rate(newRate)
        case .Duration(let duration):
            let newDuration = min(duration + x, 0.0)
            self = .Duration(newDuration)
        }
    }
}
```

Then you could just call:

``` swift
label.speed.incrementBy(7)
```

**EDIT:** Fixed `min` function calls, probably.

**Comment by GoodBrue** [comment]
I get the error "Cannot call value of non-function type 'CGFloat'" on this line:

```
    let newRate = CGFloat.min(rate + x, 0.0)
```

Same for newDuration.

How about:

```
    let newRate = rate + x < 0.0 ? 0.0 : rate + x
```

This doesn't help me anyway. I need to use the "rate" var later. I guess I'll save the rate var in my view controller instead of reading it out of MarqueeLabel.speed each time and do the math on my var. Then I can just set the speed like so:

```
    label.speed = MarqueeLabel.SpeedLimit.Rate(rate)
```

**Comment by cbpowell** [comment]
Well like the caveat noted, I never ran that code and wrote it outside of Xcode. I think you can just call `min` (I use it similarly in MarqueeLabel)...I've updated the prior comment.

But that function was just an example, and it's all in "your" codebase since it's an extension, so you can tweak it however you like to get what you need. You could maybe instead do (again, haven't tested this at all):

``` swift
// Caveat: I didn't write this in Xcode...
// It may need to be fixed and definitely needs to be tested
extension SpeedLabel {
    mutating func incrementBy(x: CGFloat) -> CGFloat {
        switch self {
        case .Rate(let rate):
            let newRate = min(rate + x, 0.0)
            self = .Rate(newRate)
            return newRate
        case .Duration(let duration):
            let newDuration = min(duration + x, 0.0)
            self = .Duration(newDuration)
            return newDuration
        }
    }
}
```

So now the function changes the rate or duration, and also returns the new rate/duration. You could use it like:

``` swift
var speed = label.speed
let newRate = speed.incrementBy(7)
label.speed = speed
// use newRate however you need
```

You could also add another function to the extension to _just_ get the value in the enum:

``` swift
extension SpeedLabel {
    mutating func incrementBy(x: CGFloat) -> CGFloat {
        // ...
    }

    func value() -> CGFloat {
        switch self {
        case .Rate(let rate):
            return rate
        case .Duration(let duration):
            return duration
        }
    }
}
```

There's probably a fancier way to do that, but I think that would work too.

**Comment by GoodBrue** [comment]
Thanks for your help. I'm going with this:

```
    var rate = label.speed.value() + x
    if rate < 0.0 { rate = 0.0 }
    label.speed = .Rate(rate)
    rateLabel.text = String(rate)
```

**Comment by GoodBrue** [comment]
Is there a way to update the speed without the label scroll starting over from the beginning?

**Comment by cbpowell** [comment]
Glad to help!

It depends - the only way you could do it now would be to override the `labelReturnedToHome` function ([here](https://github.com/cbpowell/MarqueeLabel-Swift/blob/master/Classes/MarqueeLabel.swift#L1071-L1074)) in a subclass of MarqueeLabel and perform the `speed` change in that overridden function. The change to the `speed` property would still technically cause a jump, but it shouldn't be noticeable as the label is already at the beginning (same as the end). You would presumably need to queue up the new `speed` somehow.

You could possibly also comment out the `updateAndScroll()` call [on this line](https://github.com/cbpowell/MarqueeLabel-Swift/blob/master/Classes/MarqueeLabel.swift#L108), and thus the changes to the `speed` property wouldn't cause a jump to the beginning. I _think_ the change would take effect on the next animation loop.

**Comment by GoodBrue** [comment]
Commenting out updateAndScroll() in speed.didSet() doesn't work. The scroll speed doesn't appear to change after the speed value update.

I think in the first suggestion you're proposing, the speed would only change when the label is at the start position. That won't be any better for me. I added a pan gesture recognizer to my MarqueeLabel and I'm trying to change the speed as the user drags across it. Right now the label jiggles back to the starting position many times during the drag.

A visual improvement would be to comment out the updateAndScroll() in speed.didSet(), make updateAndScroll() public and call it from the pan gesture recognizer when the pan gesture state is UIGestureRecognizerState.Ended. This way you would see a jump back to start only once, but it would be better if I could update the label speed during each call to the pan gesture handler without the scroll starting from the beginning each time.

I'd rather not mess with the internals of someone else's class if I don't have to. I could break something.

**Comment by cbpowell** [comment]
Correct, there's not currently a way to change the speed of the scrolling animation on the fly.

What you're looking to do is something I've considered before - [see this 1+ year old issue](https://github.com/cbpowell/MarqueeLabel/issues/71#issuecomment-56045866) on the Objective-C version of MarqueeLabel. MarqueeLabel works using Core Animation, so the way to "move" the text around via the animation is to manipulate the animating layer(s).

To control MarqueeLabel via a pan gesture, you'd want to do something similar to [what David Rönnqvist does here](http://ronnqvi.st/controlling-animation-timing/#controlling-animation-timing) with a UISlider. The gesture handler would need to adjust the `timeOffset` of both `sublabel.layer` and `self.layer.mask` as appropriate. There are probably some more tricky bits too, like keeping the `timeOffset` within sane limits and/or looping around.

It would be a neat addition! And there's no risk in breaking something, you can always revert to the last commit!

**Comment by GoodBrue** [comment]
Ahhh! Learn animation? Nooooo! My head hurts just thinking about it! The hacks we worked out will be good enough.

**Pull request merged**
