### PR TITLE
Add carthage support

### PR DESCRIPTION
**Pull request by toshi0383**
Carthage support for tvOS has been removed in 80c46a770e25fbf99c119d3f17c23b1de377aaf4.
Sorry I didn't mention about carthage in the last PR.
This change introduces carthage support for both iOS and tvOS.

Please take a look😉

### CODE REVIEW

**Comment by cbpowell** [comment]
Oh yeah that's totally my fault! I pulled it all out, not even thinking about what it was. Thanks for the new PR!

**Comment by toshi0383** [comment]
Would you mind creating a new release for this ?
Carthage needs a tag pushed unless users specify branch name or commit hash in their Cartfile.

**Comment by cbpowell** [comment]
Yep no problem - created [release 2.5.2](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.5.2).

**Comment by toshi0383** [comment]
Thank you !!

**Pull request merged**
